// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cqzcknweknmjmvigivdj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNxemNrbndla25tam12aWdpdmRqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUxMjI2ODIsImV4cCI6MjA3MDY5ODY4Mn0.eDtVKLIzRD9W8vo4u51rGG4wdwVz1OM-0ErdEMG_lS8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});